"""Exact computations with Aoki's gap group for Section 5 of the paper
"The Hodge conjecture for Fermat varieties of degree 35".

Requirements: python3 (>= 3.8).  Everything below is exact integer arithmetic in pure Python.
python-flint is optional: it is used only for an independent computation of the lattice indices by
Hermite and Smith normal forms (FLINT), which is compared with the pure-Python results.

    python3 gap.py                (about 20 seconds)

Notation (Section 5.1 of the paper).  For m >= 2, R_m is the free abelian group on the symbols (y),
y in Z/m - {0}; an element x = sum_y c_y (y) is stored as a dictionary {y: c_y} with 1 <= y <= m-1, and
len(x) = sum_y c_y.  For a character a = (a_0, ..., a_{n+1}) put u(a) = (a_0) + ... + (a_{n+1}).
    K_m = { x : sum_y c_y <ty> = (m/2) len(x) for every unit t mod m },   <ty> in {1, ..., m-1},
    B_m = { x in K_m : len(x) even }       (Lemma 5.1: the group generated by the u(a), a Hodge),
    D_m = the subgroup generated by the pairs (y) + (-y),
    S_m = D_m + the subgroup generated by the u(sigma_{p,i}), sigma_{p,i} Aoki's standard characters:
          sigma_{p,i} = (i, i+m/p, ..., i+(p-1)m/p, -p i)   (p an odd prime, p | m, m > p, 0 < i < m/p),
          sigma_{2,i} = (i, i+m/2, -2i, m/2)                 (m even, m > 2, 0 < i < m/2).
The six representatives (Lemma 5.7) are
    rho_12 = (1,6,8,9), rho_15 = (1,6,10,13), rho_20 = (1,4,17,18), rho_21 = (1,4,18,19),
    rho_28 = (1,9,21,25), rho_35 = beta = (1,2,16,21,30,17,22,31),
and for q | m the character rho_q^(m) = (m/q) rho_q of level m has the entries (m/q) <a_i>.
The order parity nu_l(x) (Lemma 5.6) is the sum mod 2 of the c_y over the y of order exactly l.

Part A  (Lemmas 5.6, 5.7) for q in {12, 15, 20, 21, 28, 35}: rho_q is a Hodge character of level q;
        q is a product of two elements of P = {4, 3, 5, 7, 11, ...} and Q(q) = {q}; nu_l vanishes on all
        generators of S_q and nu_l(rho_q) = 1 for l = 3, 5, 5, 7, 4, 5; B_q = S_q + Z u(rho_q) and
        2 u(rho_q) lies in S_q, so B_q/S_q = Z/2.  Also: the element (1,4,16,9,15,18) of level 21 is a
        Hodge character with nu_7 = 1, and the entries of (1,9,25,12,20,24) add up to 91 (not 0 mod 28).
Part B  (Proposition 5.8, Remark 5.9) for m = 35k, 1 <= k <= 10, with Q(m) the set of q in
        {12, 15, 20, 21, 28, 35} dividing m:
          Q(m) = {d | m : d > 1, mu'(d) = 1} and |Q(m)| = 2^(r-1) - 1 (r = number of divisors of m in P);
          (a) B_m = S_m + sum_{q in Q(m)} Z u(rho_q^(m));
          (b) 2 u(rho_q^(m)) lies in S_m, and B_m/S_m = (Z/2)^|Q(m)| with basis the classes of the rho_q^(m);
              u(rho_q^(m)) + t u(rho_q^(m)) lies in S_m for every unit t (so x + t x lies in S_m for x in B_m);
          (c) [B_m : S_m + sum_{q in Q(m), q != 35} Z u(rho_q^(m))] = 2;
        the order parities nu_l (l in {3, 4, 5, 7}, gcd(l, m/l) = 1) vanish on S_m, and for m != 280, 315
        they separate the classes of the rho_q^(m).
Part C  (Remark 7.5) u(gamma) - u(2 beta) lies in S_70 and u(delta) - u(6 beta) lies in S_210, where
        gamma = (1,20,24,42,61,62) and delta = (2,9,129,142,168,180); nu_5 = 1 on beta, gamma, delta.
Part D  (Remark 5.10) for the ten levels: no Hodge character with four entries lies in the class of
        rho_35^(m) modulo L'_m = S_m + sum_{q != 35} Z u(rho_q^(m)); for odd m also none with six entries;
        for even m the character (m/70) gamma, with six entries, does.

How (a) is proved.  Every generator of L_m = S_m + sum_q Z u(rho_q^(m)) is checked to lie in B_m.  The
|(Z/m)^x|/2 linear forms defining K_m (t and -t give the same form) have full rank modulo the prime
2^61 - 1, so K_m has rank r_m = m - 1 - |(Z/m)^x|/2.  An echelon basis of L+_m = L_m + Z (m/2) (m even),
resp. L+_m = L_m (m odd), is computed from the generators by unimodular row operations; it has r_m rows,
and for every prime p dividing the product of its pivots its rank modulo p is r_m.  So the maximal minors
of this basis have no common prime factor, L+_m is saturated of rank r_m, and L+_m = K_m.  Since L_m lies in
B_m, [K_m : B_m] <= 2 (with equality iff m is even) and 2 (m/2) lies in L_m, this gives L_m = B_m.
How (b), (c) are proved.  2 u(rho_q^(m)) is reduced to 0 by an echelon basis of S_m.  For each q in Q(m) a
homomorphism phi_q(x) = sum_{y in W_q} c_y + b_q len(x)/2 mod 2 on B_m is computed (by linear algebra over
F_2) and checked to vanish on all generators of S_m and to satisfy phi_q(rho_q'^(m)) = [q = q'].
How Part D is proved.  phi_35 is chosen with b_35 = 0 and W_35 a union of the sets {y : ord(y) = k}, so it
is invariant under (Z/m)^x; every orbit of (Z/m)^x on the Hodge characters contains one with an entry
dividing m; all Hodge characters with four (resp. six) entries having an entry g | m, g < m, are listed
exactly (meet in the middle on the exact integer key sum_k 2 sum_i <t_k a_i> 2^(w k)), and phi_35 is 0 on
all of them.

Exit status 0 if and only if every check passes.
"""
import sys
import time
from itertools import combinations_with_replacement
from math import gcd

try:
    import flint
except ImportError:          # the independent index computation is skipped
    flint = None

checks = []


def check(name, cond):
    checks.append((name, bool(cond)))
    print(("PASS  " if cond else "FAIL  ") + name)
    return bool(cond)


# ====================================================================== arithmetic
def units(m):
    return [t for t in range(1, m) if gcd(t, m) == 1]


def half_units(m):
    """one unit from each pair {t, -t}"""
    return [t for t in units(m) if 2 * t < m] if m > 2 else [1]


def prime_factors(n):
    out, p = [], 2
    while p * p <= n:
        if n % p == 0:
            out.append(p)
            while n % p == 0:
                n //= p
        p += 1
    if n > 1:
        out.append(n)
    return out


def divisors(n):
    return [d for d in range(1, n + 1) if n % d == 0]


def P_divisors(m):
    """the divisors of m in P = {4} u {odd primes}"""
    out = [p for p in prime_factors(m) if p != 2]
    if m % 4 == 0:
        out.append(4)
    return sorted(out)


def mu_prime(d):
    """(-1)^r if d is a product of r distinct elements of P = {4} u {odd primes}, and 0 otherwise"""
    r, n = 0, d
    if n % 2 == 0:
        if n % 4 or (n // 4) % 2 == 0:
            return 0
        n //= 4
        r += 1
    for p in prime_factors(n):
        if n % (p * p) == 0:
            return 0
        n //= p
        r += 1
    return (-1) ** r


def order(y, m):
    return m // gcd(y, m)


def u(a, m):
    """u(a) in R_m"""
    v = {}
    for y in a:
        y %= m
        assert y, "zero entry"
        v[y] = v.get(y, 0) + 1
    return v


def length(x):
    return sum(x.values())


def add(x, z, k=1):
    out = dict(x)
    for y, c in z.items():
        w = out.get(y, 0) + k * c
        if w:
            out[y] = w
        else:
            out.pop(y, None)
    return out


def scal(k, x):
    return {y: k * c for y, c in x.items()} if k else {}


def in_K(x, m):
    return all(2 * sum(c * ((t * y) % m) for y, c in x.items()) == m * length(x) for t in half_units(m))


def in_B(x, m):
    """Lemma 5.1 (the conditions for t and -t coincide)"""
    return length(x) % 2 == 0 and in_K(x, m)


def is_hodge(a, m):
    """a in B^n_m with n = len(a) - 2 even (Theorem 2.1(iii)); t = 1 gives sum(a) = 0 mod m"""
    return len(a) % 2 == 0 and all(y % m for y in a) and in_B(u(a, m), m)


def inflate(a, q, m):
    """the character (m/q) a of level m (Lemma 2.3(c)): entries (m/q) <a_i>"""
    return tuple((m // q) * (y % q) for y in a)


def standard_characters(m):
    out = []
    for p in prime_factors(m):
        if m == p:
            continue
        d = m // p
        for i in range(1, d):
            if p == 2:
                out.append(((2, i), (i, i + d, m - 2 * i, d)))
            else:
                out.append(((p, i), tuple(i + k * d for k in range(p)) + (m - p * i,)))
    return out


def pair_vectors(m):
    return [u((y, m - y), m) for y in range(1, m // 2 + 1)]


def S_generators(m):
    return pair_vectors(m) + [u(a, m) for _, a in standard_characters(m)]


def nu(x, l, m):
    """Lemma 5.6: the sum mod 2 of the coefficients c_y over the y of order exactly l"""
    return sum(c for y, c in x.items() if order(y, m) == l) % 2


def nu_hypothesis(l, m):
    """l in P = {4} u {odd primes}, l | m and gcd(l, m/l) = 1"""
    in_P = l == 4 or (l > 2 and prime_factors(l) == [l])
    return in_P and m % l == 0 and gcd(l, m // l) == 1


# ====================================================================== lattices (pure Python)
def xgcd(a, b):
    x0, y0, x1, y1 = 1, 0, 0, 1
    while b:
        q = a // b
        a, b = b, a - q * b
        x0, x1 = x1, x0 - q * x1
        y0, y1 = y1, y0 - q * y1
    if a < 0:
        a, x0, y0 = -a, -x0, -y0
    return a, x0, y0


def lin(x, a, y, b):
    """x a + y b for sparse vectors a, b"""
    out = {k: x * v for k, v in a.items()} if x else {}
    if y:
        for k, v in b.items():
            w = out.get(k, 0) + y * v
            if w:
                out[k] = w
            else:
                out.pop(k, None)
    return {k: v for k, v in out.items() if v}


class Echelon:
    """An echelon basis (the pivot of a row is its smallest coordinate with a nonzero entry; pivot entries
    are positive) of the subgroup generated by the inserted vectors.  Only unimodular row operations are
    used, so the rows always generate exactly the subgroup spanned by the inserted vectors."""

    def __init__(self):
        self.rows = {}

    def copy(self):
        e = Echelon()
        e.rows = {j: dict(r) for j, r in self.rows.items()}
        return e

    def insert(self, v):
        v = {k: c for k, c in v.items() if c}
        while v:
            j = min(v)
            if j not in self.rows:
                self.rows[j] = v if v[j] > 0 else {k: -c for k, c in v.items()}
                return
            b = self.rows[j]
            a, c = b[j], v[j]
            if c % a == 0:
                v = lin(1, v, -(c // a), b)
            else:
                g, x, y = xgcd(a, c)                     # g = x a + y c > 0
                self.rows[j] = lin(x, b, y, v)           # new pivot entry g
                v = lin(c // g, b, -(a // g), v)         # (x y; c/g -a/g) has determinant -1

    def contains(self, v):
        v = {k: c for k, c in v.items() if c}
        while v:
            j = min(v)
            if j not in self.rows or v[j] % self.rows[j][j]:
                return False
            v = lin(1, v, -(v[j] // self.rows[j][j]), self.rows[j])
        return True

    def rank(self):
        return len(self.rows)

    def pivot_product(self):
        out = 1
        for j, r in self.rows.items():
            out *= r[j]
        return out

    def rank_mod(self, p):
        """rank of the basis modulo the prime p: the rows whose pivot entry is a unit mod p are independent
        mod p; the others are reduced by them and their residues are eliminated among themselves"""
        good = sorted(j for j, r in self.rows.items() if r[j] % p)
        residues = []
        for j0 in sorted(self.rows):
            if self.rows[j0][j0] % p:
                continue
            v = {k: c % p for k, c in self.rows[j0].items() if c % p}
            for j in good:
                if v.get(j, 0):
                    b = self.rows[j]
                    f = v[j] * pow(b[j], -1, p) % p
                    v = {k: c % p for k, c in lin(1, v, -f, b).items() if c % p}
            residues.append(v)
        return len(good) + rank_mod_p(residues, p)


def rank_mod_p(vectors, p):
    """rank modulo p of a list of sparse vectors (Gaussian elimination)"""
    basis = {}
    for v in vectors:
        v = {k: c % p for k, c in v.items() if c % p}
        while v:
            j = min(v)
            if j not in basis:
                inv = pow(v[j], -1, p)
                basis[j] = {k: c * inv % p for k, c in v.items()}
                break
            v = {k: c % p for k, c in lin(1, v, -v[j], basis[j]).items() if c % p}
    return len(basis)


BIG_PRIME = 2 ** 61 - 1


def rank_K(m):
    """(r_m, number of linear forms, their rank modulo 2^61 - 1); the forms are x -> sum_y c_y (2<ty> - m)"""
    forms = [{y: 2 * ((t * y) % m) - m for y in range(1, m)} for t in half_units(m)]
    return (m - 1) - len(forms), len(forms), rank_mod_p(forms, BIG_PRIME)


def prove_equal_to_B(m, gens):
    """Proves that the subgroup L generated by gens equals B_m (see the docstring).
    Returns (ok, r_m, echelon basis of L, pivot product of L+, primes for which the rank was checked)."""
    ok = all(in_B(g, m) for g in gens)
    r, nforms, rk = rank_K(m)
    ok &= rk == nforms
    E = Echelon()
    for g in gens:
        E.insert(g)
    Ep = E.copy()
    if m % 2 == 0:
        ok &= in_K({m // 2: 1}, m) and not in_B({m // 2: 1}, m) and {m // 2: 2} in gens
        Ep.insert({m // 2: 1})
    ok &= Ep.rank() == r
    D = Ep.pivot_product()
    primes = prime_factors(D)
    ok &= all(Ep.rank_mod(p) == r for p in primes)
    return ok, r, E, D, primes


# ====================================================================== parity homomorphisms on B_m
def f2_solve(equations, nvars):
    """equations: list of (bitmask over nvars variables, right side); returns one solution or None"""
    basis = {}
    for mask, rhs in equations:
        for piv in sorted(basis, reverse=True):
            if (mask >> piv) & 1:
                bm, br = basis[piv]
                mask ^= bm
                rhs ^= br
        if mask == 0:
            if rhs:
                return None
            continue
        piv = mask.bit_length() - 1
        for q in list(basis):
            bm, br = basis[q]
            if (bm >> piv) & 1:
                basis[q] = (bm ^ mask, br ^ rhs)
        basis[piv] = (mask, rhs)
    sol = 0
    for piv, (mask, rhs) in basis.items():
        if rhs:
            sol |= 1 << piv
    return sol


def parity_homomorphism(zero_on, targets, classes):
    """phi(x) = sum_{y in W} c_y + b len(x)/2 mod 2 with W a union of the given disjoint classes, phi = 0 on
    zero_on and phi(x) = e for (x, e) in targets; returns (W, b) or None"""
    nv = len(classes) + 1

    def eq(x):
        mask = 0
        for i, cl in enumerate(classes):
            if sum(c for y, c in x.items() if y in cl) % 2:
                mask |= 1 << i
        if (length(x) // 2) % 2:
            mask |= 1 << (nv - 1)
        return mask

    sol = f2_solve([(eq(x), 0) for x in zero_on] + [(eq(x), e) for x, e in targets], nv)
    if sol is None:
        return None
    W = set()
    for i, cl in enumerate(classes):
        if (sol >> i) & 1:
            W |= set(cl)
    return W, (sol >> (nv - 1)) & 1


def phi_eval(x, W, b):
    return (sum(c for y, c in x.items() if y in W) + b * (length(x) // 2)) % 2


def order_classes(m):
    out = {}
    for y in range(1, m):
        out.setdefault(order(y, m), set()).add(y)
    return [out[k] for k in sorted(out)]


def is_union_of_order_classes(W, m):
    return all({y for y in range(1, m) if order(y, m) == order(z, m)} <= W for z in W)


def describe(W, b, m):
    if is_union_of_order_classes(W, m):
        text = "entries of order " + ", ".join(map(str, sorted({order(y, m) for y in W})))
    else:
        text = "W = the %d residues {%s}" % (len(W), ",".join(map(str, sorted(W))))
    return text + (" + len/2" if b else "")


def f2_rank(rows):
    """rank over F_2 of a list of 0/1 tuples"""
    return rank_mod_p([{i: v for i, v in enumerate(r) if v} for r in rows], 2)


# ====================================================================== the data
BETA = (1, 2, 16, 21, 30, 17, 22, 31)
REPS = {12: (1, 6, 8, 9), 15: (1, 6, 10, 13), 20: (1, 4, 17, 18), 21: (1, 4, 18, 19), 28: (1, 9, 21, 25), 35: BETA}
ELL = {12: 3, 15: 5, 20: 5, 21: 7, 28: 4, 35: 5}
LEVELS = [35 * k for k in range(1, 11)]
GAMMA = (1, 20, 24, 42, 61, 62)
DELTA = (2, 9, 129, 142, 168, 180)


def fmt(a):
    return "(" + ",".join(map(str, a)) + ")"


# ====================================================================== independent index computation (FLINT)
def flint_indices(m, generator_lists):
    """for each list of generators of a subgroup L of K_m of full rank: (product of the pivots of the Hermite
    normal form, product of the Smith invariants = [K_m : L])"""
    N = m - 1
    out = []
    for gens in generator_lists:
        entries = []
        for g in gens:
            row = [0] * N
            for y, c in g.items():
                row[y - 1] = c
            entries.extend(row)
        H = flint.fmpz_mat(len(gens), N, entries).hnf()
        Hl = [[int(v) for v in r] for r in H.tolist() if any(r)]
        piv = 1
        for r in Hl:
            piv *= next(v for v in r if v)
        Sm = flint.fmpz_mat(len(Hl), N, [v for r in Hl for v in r]).snf()
        prod = 1
        for i in range(len(Hl)):
            prod *= int(Sm[i, i])
        out.append((piv, abs(prod)))
    return out


# ====================================================================== Part A
def part_A():
    print("Part A. The six representatives (Lemmas 5.6 and 5.7)")
    for q, rho in REPS.items():
        check("rho_%d = %s is a Hodge character of level %d and dimension %d" % (q, fmt(rho), q, len(rho) - 2),
              is_hodge(rho, q))
        check("q = %d is the product of the two elements %s of P, and {d | q : d > 1, mu'(d) = 1} = {%d}"
              % (q, P_divisors(q), q),
              len(P_divisors(q)) == 2 and P_divisors(q)[0] * P_divisors(q)[1] == q
              and [d for d in divisors(q) if d > 1 and mu_prime(d) == 1] == [q])
        l = ELL[q]
        gens = S_generators(q)
        ent = [y for y in rho if order(y, q) == l]
        check("q = %d, l = %d: gcd(l, q/l) = 1, nu_%d vanishes on the %d generators of S_%d, and rho_%d has exactly "
              "one entry of order %d, namely %s" % (q, l, l, len(gens), q, q, l, ent),
              nu_hypothesis(l, q) and all(nu(g, l, q) == 0 for g in gens) and len(ent) == 1)
        ok, r, E, D, primes = prove_equal_to_B(q, gens + [u(rho, q)])
        ES = Echelon()
        for g in gens:
            ES.insert(g)
        check("q = %d: B_%d = S_%d + Z u(rho_%d) (rank %d), 2 u(rho_%d) lies in S_%d and u(rho_%d) does not, "
              "so B_%d/S_%d = Z/2" % (q, q, q, q, r, q, q, q, q, q),
              ok and ES.contains(scal(2, u(rho, q))) and not ES.contains(u(rho, q)))
    x21 = (1, 4, 16, 9, 15, 18)
    check("the element %s of level 21 is a Hodge character of dimension 4 with nu_7 = 1" % fmt(x21),
          is_hodge(x21, 21) and nu(u(x21, 21), 7, 21) == 1)
    x28 = (1, 9, 25, 12, 20, 24)
    check("the entries of %s add up to %d, which is not divisible by 28" % (fmt(x28), sum(x28)),
          sum(x28) == 91 and sum(x28) % 28 != 0)


# ====================================================================== Part B
def part_B(results):
    print()
    print("Part B. The ten levels m = 35k, 1 <= k <= 10 (Proposition 5.8, Remark 5.9)")
    for m in LEVELS:
        Q = [q for q in sorted(REPS) if m % q == 0]
        j = len(Q)
        rP = len(P_divisors(m))
        r_m = (m - 1) - len(half_units(m))
        print("m = %d: Q(m) = {%s}, rank r_m = %d" % (m, ", ".join(map(str, Q)), r_m))
        check("m = %d: Q(m) = {d | m : d > 1, mu'(d) = 1}; m has %d divisors in P and |Q(m)| = 2^%d - 1 = %d"
              % (m, rP, rP - 1, j), Q == [d for d in divisors(m) if d > 1 and mu_prime(d) == 1] and j == 2 ** (rP - 1) - 1)
        Sg = S_generators(m)
        chars = {q: inflate(REPS[q], q, m) for q in Q}
        reps = {q: u(chars[q], m) for q in Q}
        check("m = %d: the %d generators of S_m lie in B_m, and the rho_q^(m) are Hodge characters: %s"
              % (m, len(Sg), ", ".join("rho_%d^(m) = %s" % (q, fmt(chars[q])) for q in Q)),
              all(in_B(x, m) for x in Sg) and all(is_hodge(chars[q], m) for q in Q))
        ok, r, E, D, primes = prove_equal_to_B(m, Sg + [reps[q] for q in Q])
        check("m = %d: (a) B_m = S_m + sum_q Z u(rho_q^(m)): the echelon basis of L+_m has %d rows, pivot product %d%s"
              % (m, r, D, (", full rank modulo %s" % " and ".join(map(str, primes))) if primes else ""), ok and r == r_m)
        ES = Echelon()
        for g in Sg:
            ES.insert(g)
        check("m = %d: (b) 2 u(rho_q^(m)) lies in S_m for q in Q(m)" % m, all(ES.contains(scal(2, reps[q])) for q in Q))
        phis = {}
        for q in Q:
            targets = [(reps[q2], 1 if q2 == q else 0) for q2 in Q]
            f = parity_homomorphism(Sg, targets, order_classes(m))
            if f is None:
                f = parity_homomorphism(Sg, targets, [{y} for y in range(1, m)])
            phis[q] = f
        okf = all(f is not None for f in phis.values())
        if okf:
            for q in Q:
                W, b = phis[q]
                okf &= all(phi_eval(g, W, b) == 0 for g in Sg)
                okf &= all(phi_eval(reps[q2], W, b) == (1 if q2 == q else 0) for q2 in Q)
        check("m = %d: (b) parity homomorphisms vanishing on S_m with phi_q(rho_q'^(m)) = [q = q'] (%s); "
              "so B_m/S_m = (Z/2)^%d" % (m, "; ".join("phi_%d: %s" % (q, describe(phis[q][0], phis[q][1], m)) for q in Q)
                                         if okf else "none exists", j), okf)
        check("m = %d: (b) u(rho_q^(m)) + t u(rho_q^(m)) lies in S_m for q in Q(m) and all %d units t; with (a) and the "
              "stability of S_m under units this gives x + t x in S_m for all x in B_m" % (m, len(units(m))),
              all(ES.contains(add(reps[q], {(t * y) % m: c for y, c in reps[q].items()})) for q in Q for t in units(m)))
        others = [reps[q] for q in Q if q != 35]
        Lp = ES.copy()
        for x in others:
            Lp.insert(x)
        check("m = %d: (c) [B_m : S_m + sum_{q != 35} Z u(rho_q^(m))] = 2" % m,
              okf and not Lp.contains(reps[35]) and ES.contains(scal(2, reps[35])))
        valid = [l for l in (3, 4, 5, 7) if nu_hypothesis(l, m)]
        table = {l: tuple(nu(reps[q], l, m) for q in Q) for l in valid}
        sep = f2_rank(list(table.values())) == j
        check("m = %d: Lemma 5.6 for l in %s: nu_l vanishes on all generators of S_m; (nu_l(rho_q^(m)))_q = %s; "
              "these %s the classes of the rho_q^(m)" % (m, valid, table, "separate" if sep else "do not separate"),
              all(nu(g, l, m) == 0 for l in valid for g in Sg) and sep == (m not in (280, 315)))
        if flint is not None:
            gensL = Sg + [reps[q] for q in Q]
            half = [{m // 2: 1}] if m % 2 == 0 else []
            res = flint_indices(m, [Sg, Sg + others, gensL, gensL + half])
            KB = 2 if m % 2 == 0 else 1
            pure = [ES.pivot_product(), Lp.pivot_product(), E.pivot_product(), D]
            check("m = %d: FLINT: [K_m : L] = %s for L = S_m, L'_m, L_m, L+_m (expected %s); Hermite pivot "
                  "products %s agree with the pure-Python echelon bases"
                  % (m, [x[1] for x in res], [KB * 2 ** j, KB * 2, KB, 1], [x[0] for x in res]),
                  [x[1] for x in res] == [KB * 2 ** j, KB * 2, KB, 1] and [x[0] for x in res] == pure)
        results[m] = dict(Q=Q, reps=reps, phis=phis, ES=ES)


# ====================================================================== Part C
def part_C(results):
    print()
    print("Part C. gamma and delta (Remark 7.5)")
    x = add(u(GAMMA, 70), u(inflate(BETA, 35, 70), 70), -1)
    check("u(gamma) - u(2 beta) lies in S_70; gamma = %s, 2 beta = %s" % (fmt(GAMMA), fmt(inflate(BETA, 35, 70))),
          is_hodge(GAMMA, 70) and results[70]["ES"].contains(x))
    y = add(u(DELTA, 210), u(inflate(BETA, 35, 210), 210), -1)
    check("u(delta) - u(6 beta) lies in S_210; delta = %s, 6 beta = %s" % (fmt(DELTA), fmt(inflate(BETA, 35, 210))),
          is_hodge(DELTA, 210) and results[210]["ES"].contains(y))
    ent = [[z for z in a if order(z, m) == 5] for a, m in ((BETA, 35), (GAMMA, 70), (DELTA, 210))]
    check("the entries of order 5 of beta, gamma, delta are %s, one each; 5 satisfies Lemma 5.6 at 35, 70, 210" % ent,
          ent == [[21], [42], [168]] and all(nu_hypothesis(5, m) for m in (35, 70, 210)))


# ====================================================================== Part D
def hodge_with_divisor(m, L):
    """All Hodge characters of level m with L entries (L = 4 or 6), up to order, having an entry equal to a
    divisor g < m of m.  Meet in the middle: a tuple is split as (g, x_1, ..., x_{L/2-1}) and
    (y_1 <= ... <= y_{L/2}).  The key sum_k 2 sum_i <t_k a_i> 2^(w k) (t_k the units < m/2) is exact, as
    each field is < 2^w, and a tuple is a Hodge character iff its key equals sum_k L m 2^(w k)."""
    T = half_units(m)
    h = L // 2
    w = (2 * L * m).bit_length() + 1
    P = [0] * m
    for y in range(1, m):
        v = 0
        for k, t in enumerate(T):
            v |= (2 * ((t * y) % m)) << (w * k)
        P[y] = v
    target = sum((L * m) << (w * k) for k in range(len(T)))
    left = {}
    for g in divisors(m)[:-1]:
        for xs in combinations_with_replacement(range(1, m), h - 1):
            left.setdefault(P[g] + sum(P[x] for x in xs), []).append((g,) + xs)
    listed = set()
    for ys in combinations_with_replacement(range(1, m), h - 1):
        base = target - sum(P[y] for y in ys)
        last0 = ys[-1] if ys else 1
        for z in range(last0, m):
            for lt in left.get(base - P[z], ()):
                listed.add(tuple(sorted(lt + ys + (z,))))
    return listed


def part_D(results):
    print()
    print("Part D. Hodge characters with four and six entries in the class of beta (Remark 5.10)")
    for m in LEVELS:
        reps = results[m]["reps"]
        W, b = results[m]["phis"][35]
        inv = b == 0 and is_union_of_order_classes(W, m)
        f4 = hodge_with_divisor(m, 4)
        if m % 2 == 0:
            check("m = %d: phi_35 (%s) is invariant under (Z/m)^x and vanishes on the %d Hodge characters with four "
                  "entries having an entry dividing m; so no character in B^2_m lies in the class of beta"
                  % (m, describe(W, b, m), len(f4)), inv and all(phi_eval(u(a, m), W, b) == 0 for a in f4))
            g = inflate(GAMMA, 70, m)
            check("m = %d: (m/70) gamma = %s lies in B^4_m and in the class of beta (u((m/70) gamma) - u(rho_35^(m)) "
                  "lies in S_m)" % (m, fmt(g)), is_hodge(g, m) and results[m]["ES"].contains(add(u(g, m), reps[35], -1)))
        else:
            f6 = hodge_with_divisor(m, 6)
            check("m = %d: phi_35 (%s) is invariant under (Z/m)^x and vanishes on the %d (resp. %d) Hodge characters "
                  "with four (resp. six) entries having an entry dividing m; so no character in B^2_m or B^4_m lies in "
                  "the class of beta" % (m, describe(W, b, m), len(f4), len(f6)),
                  inv and all(phi_eval(u(a, m), W, b) == 0 for a in f4 | f6))


# ====================================================================== main
def main():
    t0 = time.time()
    results = {}
    part_A()
    part_B(results)
    part_C(results)
    part_D(results)
    bad = [nm for nm, ok in checks if not ok]
    print()
    print("all %d checks passed" % len(checks) if not bad else "%d of %d checks FAILED" % (len(bad), len(checks)))
    print("(%s; %.1f s)" % ("python-flint %s" % flint.__version__ if flint else "python-flint not available: the "
                            "independent index computation was skipped", time.time() - t0), file=sys.stderr)
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
